name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest httpx

      - name: Run simple tests
        env:
          OLLAMA_API_KEY: "dummy_key_for_testing"
        run: |
          # Simple syntax check and import test
          python -c "import app.main; print('Import successful')"

  build-and-push:
    needs: test
    if: gitea.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://git.n1c.lol
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            git.n1c.lol/${{ gitea.repository }}:latest
            git.n1c.lol/${{ gitea.repository }}:${{ gitea.event.release.tag_name }}
